### ISSUE TITLE
Does not remember column selection

### ISSUE THREAD

**Issue by boboofid** [GeertjanWielenga/CheatSheets#1]
When I right click on the "Expands To..." column it allows me to uncheck it to hide the column. 

If, after doing so, I close NetBeans and reopen it the "Expands To..." column reappears.

I am choosing to hide the column because it is too small to show anything useful to me and I would like more space for the description.

**Comment by vonloxley** [comment]
:+1: Same here.

**Comment by GeertjanWielenga** [comment]
Yeah, not sure, hard to do. Lots of squeeze for not much juice.
